#############################################################################
# Makefile for building: BalancedTree
# Generated by qmake (3.1) (Qt 5.12.0)
# Project:  BalancedTree.pro
# Template: app
# Command: /Users/wolfgangmeyerle/QtNeu/5.12.0/clang_64/bin/qmake -o Makefile BalancedTree.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.12 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.12 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../QtNeu/5.12.0/clang_64/mkspecs/macx-clang
QMAKE         = /Users/wolfgangmeyerle/QtNeu/5.12.0/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/wolfgangmeyerle/QtNeu/5.12.0/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/wolfgangmeyerle/QtNeu/5.12.0/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = BalancedTree1.0.0
DISTDIR = /Users/wolfgangmeyerle/BalancedTree/.tmp/BalancedTree1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.12 -Wl,-rpath,@executable_path/Frameworks
LIBS          = $(SUBLIBS)    
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		point.cpp \
		quicksort.cpp 
OBJECTS       = main.o \
		point.o \
		quicksort.o
DIST          = ../QtNeu/5.12.0/clang_64/mkspecs/features/spec_pre.prf \
		../QtNeu/5.12.0/clang_64/mkspecs/qdevice.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/features/device_config.prf \
		../QtNeu/5.12.0/clang_64/mkspecs/common/unix.conf \
		../QtNeu/5.12.0/clang_64/mkspecs/common/mac.conf \
		../QtNeu/5.12.0/clang_64/mkspecs/common/macx.conf \
		../QtNeu/5.12.0/clang_64/mkspecs/common/sanitize.conf \
		../QtNeu/5.12.0/clang_64/mkspecs/common/gcc-base.conf \
		../QtNeu/5.12.0/clang_64/mkspecs/common/gcc-base-mac.conf \
		../QtNeu/5.12.0/clang_64/mkspecs/common/clang.conf \
		../QtNeu/5.12.0/clang_64/mkspecs/common/clang-mac.conf \
		../QtNeu/5.12.0/clang_64/mkspecs/qconfig.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_core.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_help.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_location.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_network.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_script.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/features/qt_functions.prf \
		../QtNeu/5.12.0/clang_64/mkspecs/features/qt_config.prf \
		../QtNeu/5.12.0/clang_64/mkspecs/macx-clang/qmake.conf \
		../QtNeu/5.12.0/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../QtNeu/5.12.0/clang_64/mkspecs/features/exclusive_builds.prf \
		../QtNeu/5.12.0/clang_64/mkspecs/features/mac/sdk.prf \
		../QtNeu/5.12.0/clang_64/mkspecs/features/toolchain.prf \
		../QtNeu/5.12.0/clang_64/mkspecs/features/mac/toolchain.prf \
		../QtNeu/5.12.0/clang_64/mkspecs/features/default_pre.prf \
		../QtNeu/5.12.0/clang_64/mkspecs/features/mac/default_pre.prf \
		../QtNeu/5.12.0/clang_64/mkspecs/features/resolve_config.prf \
		../QtNeu/5.12.0/clang_64/mkspecs/features/default_post.prf \
		../QtNeu/5.12.0/clang_64/mkspecs/features/mac/default_post.prf \
		../QtNeu/5.12.0/clang_64/mkspecs/features/mac/objective_c.prf \
		../QtNeu/5.12.0/clang_64/mkspecs/features/qml_debug.prf \
		../QtNeu/5.12.0/clang_64/mkspecs/features/mac/mac.prf \
		../QtNeu/5.12.0/clang_64/mkspecs/features/warn_on.prf \
		../QtNeu/5.12.0/clang_64/mkspecs/features/qmake_use.prf \
		../QtNeu/5.12.0/clang_64/mkspecs/features/file_copies.prf \
		../QtNeu/5.12.0/clang_64/mkspecs/features/mac/rez.prf \
		../QtNeu/5.12.0/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../QtNeu/5.12.0/clang_64/mkspecs/features/testcase_targets.prf \
		../QtNeu/5.12.0/clang_64/mkspecs/features/exceptions.prf \
		../QtNeu/5.12.0/clang_64/mkspecs/features/yacc.prf \
		../QtNeu/5.12.0/clang_64/mkspecs/features/lex.prf \
		BalancedTree.pro btree.h \
		point.h \
		quicksort.h main.cpp \
		point.cpp \
		quicksort.cpp
QMAKE_TARGET  = BalancedTree
DESTDIR       = 
TARGET        = BalancedTree

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 10.14
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))


include /Users/wolfgangmeyerle/QtNeu/5.12.0/clang_64/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

BalancedTree:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: BalancedTree.pro ../QtNeu/5.12.0/clang_64/mkspecs/macx-clang/qmake.conf ../QtNeu/5.12.0/clang_64/mkspecs/features/spec_pre.prf \
		../QtNeu/5.12.0/clang_64/mkspecs/qdevice.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/features/device_config.prf \
		../QtNeu/5.12.0/clang_64/mkspecs/common/unix.conf \
		../QtNeu/5.12.0/clang_64/mkspecs/common/mac.conf \
		../QtNeu/5.12.0/clang_64/mkspecs/common/macx.conf \
		../QtNeu/5.12.0/clang_64/mkspecs/common/sanitize.conf \
		../QtNeu/5.12.0/clang_64/mkspecs/common/gcc-base.conf \
		../QtNeu/5.12.0/clang_64/mkspecs/common/gcc-base-mac.conf \
		../QtNeu/5.12.0/clang_64/mkspecs/common/clang.conf \
		../QtNeu/5.12.0/clang_64/mkspecs/common/clang-mac.conf \
		../QtNeu/5.12.0/clang_64/mkspecs/qconfig.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_core.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_help.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_location.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_network.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_script.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../QtNeu/5.12.0/clang_64/mkspecs/features/qt_functions.prf \
		../QtNeu/5.12.0/clang_64/mkspecs/features/qt_config.prf \
		../QtNeu/5.12.0/clang_64/mkspecs/macx-clang/qmake.conf \
		../QtNeu/5.12.0/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../QtNeu/5.12.0/clang_64/mkspecs/features/exclusive_builds.prf \
		../QtNeu/5.12.0/clang_64/mkspecs/features/mac/sdk.prf \
		../QtNeu/5.12.0/clang_64/mkspecs/features/toolchain.prf \
		../QtNeu/5.12.0/clang_64/mkspecs/features/mac/toolchain.prf \
		../QtNeu/5.12.0/clang_64/mkspecs/features/default_pre.prf \
		../QtNeu/5.12.0/clang_64/mkspecs/features/mac/default_pre.prf \
		../QtNeu/5.12.0/clang_64/mkspecs/features/resolve_config.prf \
		../QtNeu/5.12.0/clang_64/mkspecs/features/default_post.prf \
		../QtNeu/5.12.0/clang_64/mkspecs/features/mac/default_post.prf \
		../QtNeu/5.12.0/clang_64/mkspecs/features/mac/objective_c.prf \
		../QtNeu/5.12.0/clang_64/mkspecs/features/qml_debug.prf \
		../QtNeu/5.12.0/clang_64/mkspecs/features/mac/mac.prf \
		../QtNeu/5.12.0/clang_64/mkspecs/features/warn_on.prf \
		../QtNeu/5.12.0/clang_64/mkspecs/features/qmake_use.prf \
		../QtNeu/5.12.0/clang_64/mkspecs/features/file_copies.prf \
		../QtNeu/5.12.0/clang_64/mkspecs/features/mac/rez.prf \
		../QtNeu/5.12.0/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../QtNeu/5.12.0/clang_64/mkspecs/features/testcase_targets.prf \
		../QtNeu/5.12.0/clang_64/mkspecs/features/exceptions.prf \
		../QtNeu/5.12.0/clang_64/mkspecs/features/yacc.prf \
		../QtNeu/5.12.0/clang_64/mkspecs/features/lex.prf \
		BalancedTree.pro
	$(QMAKE) -o Makefile BalancedTree.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
../QtNeu/5.12.0/clang_64/mkspecs/features/spec_pre.prf:
../QtNeu/5.12.0/clang_64/mkspecs/qdevice.pri:
../QtNeu/5.12.0/clang_64/mkspecs/features/device_config.prf:
../QtNeu/5.12.0/clang_64/mkspecs/common/unix.conf:
../QtNeu/5.12.0/clang_64/mkspecs/common/mac.conf:
../QtNeu/5.12.0/clang_64/mkspecs/common/macx.conf:
../QtNeu/5.12.0/clang_64/mkspecs/common/sanitize.conf:
../QtNeu/5.12.0/clang_64/mkspecs/common/gcc-base.conf:
../QtNeu/5.12.0/clang_64/mkspecs/common/gcc-base-mac.conf:
../QtNeu/5.12.0/clang_64/mkspecs/common/clang.conf:
../QtNeu/5.12.0/clang_64/mkspecs/common/clang-mac.conf:
../QtNeu/5.12.0/clang_64/mkspecs/qconfig.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_charts.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_core.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_designer.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_gui.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_help.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_location.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_network.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_positioningquick.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_qml.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_quick.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_repparser.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_script.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_service_support_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_sql.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_svg.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_webview.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_xml.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../QtNeu/5.12.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../QtNeu/5.12.0/clang_64/mkspecs/features/qt_functions.prf:
../QtNeu/5.12.0/clang_64/mkspecs/features/qt_config.prf:
../QtNeu/5.12.0/clang_64/mkspecs/macx-clang/qmake.conf:
../QtNeu/5.12.0/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../QtNeu/5.12.0/clang_64/mkspecs/features/exclusive_builds.prf:
../QtNeu/5.12.0/clang_64/mkspecs/features/mac/sdk.prf:
../QtNeu/5.12.0/clang_64/mkspecs/features/toolchain.prf:
../QtNeu/5.12.0/clang_64/mkspecs/features/mac/toolchain.prf:
../QtNeu/5.12.0/clang_64/mkspecs/features/default_pre.prf:
../QtNeu/5.12.0/clang_64/mkspecs/features/mac/default_pre.prf:
../QtNeu/5.12.0/clang_64/mkspecs/features/resolve_config.prf:
../QtNeu/5.12.0/clang_64/mkspecs/features/default_post.prf:
../QtNeu/5.12.0/clang_64/mkspecs/features/mac/default_post.prf:
../QtNeu/5.12.0/clang_64/mkspecs/features/mac/objective_c.prf:
../QtNeu/5.12.0/clang_64/mkspecs/features/qml_debug.prf:
../QtNeu/5.12.0/clang_64/mkspecs/features/mac/mac.prf:
../QtNeu/5.12.0/clang_64/mkspecs/features/warn_on.prf:
../QtNeu/5.12.0/clang_64/mkspecs/features/qmake_use.prf:
../QtNeu/5.12.0/clang_64/mkspecs/features/file_copies.prf:
../QtNeu/5.12.0/clang_64/mkspecs/features/mac/rez.prf:
../QtNeu/5.12.0/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../QtNeu/5.12.0/clang_64/mkspecs/features/testcase_targets.prf:
../QtNeu/5.12.0/clang_64/mkspecs/features/exceptions.prf:
../QtNeu/5.12.0/clang_64/mkspecs/features/yacc.prf:
../QtNeu/5.12.0/clang_64/mkspecs/features/lex.prf:
BalancedTree.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile BalancedTree.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile BalancedTree

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

benchmark: first

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp point.h \
		btree.h \
		quicksort.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

point.o: point.cpp point.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o point.o point.cpp

quicksort.o: quicksort.cpp quicksort.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o quicksort.o quicksort.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

